#!/usr/bin/env node
// Convert an episode's old caption OVERLAY props into the spoken-caption build source.
//
// Usage: node tools/captions-import.mjs [S01E003] [--apply]
//
// WHY. S01 rendered its captions as `kinetic-captions` — a rolling window of words, one
// composition, one blob of props generated by a per-episode caption-map.mjs. That predates
// `SpokenSubtitleTrack`, which is what captions.md now describes: word-timed rows, locale-
// differentiated (zh shows the whole line and lights a word, en streams), sentence cuts, one
// fixed size. Same timings underneath; a different and better-specified thing on screen.
//
// WHAT IT JOINS ON. `captions.all[.locale].json` already carries per-word start times — that is
// the expensive half and it is kept verbatim. Sentences come from the episode's `.srt`, whose
// cues ARE the authored sentence units; a word belongs to the cue whose span contains its start.
// Splitting on silence instead would invent sentence boundaries the author already chose.
//
// `e` IS NOT AN END TIME. It is the old component's emphasis COLOUR — `'brand'` or `'harsh'`,
// `KineticCaptions.tsx:29`. Reading it as a timestamp is the first thing this converter got wrong,
// and it produced `NaN` ends rather than failing, which is the good outcome of a bad assumption.
//
// A word's end is therefore the NEXT word's start, and the last word's is a per-locale default.
// The old renderer only needed starts; the new one needs a span per word, because the highlight
// IS the span.
//
// The two emphasis colours collapse to one `|*`. That is a real loss and it is deliberate: the
// spoken-caption design has a single emphasis level, chosen so that lit text means "this is the
// word the sentence is about" rather than encoding a second axis. 198 emphasised words across the
// eight files, ~2 per line, which is the density that design asks for.
import fs from 'node:fs';
import path from 'node:path';
import { REPO_ROOT, LOCALES, loadTree } from './lib.mjs';

const APPLY = process.argv.includes('--apply');
const only = process.argv.slice(2).find((a) => !a.startsWith('--'));

const srtSpans = (file) => {
  const out = [];
  const re = /(\d\d):(\d\d):(\d\d),(\d{3})\s*-->\s*(\d\d):(\d\d):(\d\d),(\d{3})/g;
  const text = fs.readFileSync(file, 'utf8');
  let m;
  while ((m = re.exec(text))) {
    const g = m.slice(1).map(Number);
    out.push([((g[0] * 60 + g[1]) * 60 + g[2]) * 1000 + g[3], ((g[4] * 60 + g[5]) * 60 + g[6]) * 1000 + g[7]]);
  }
  return out;
};

function convert(ep, locale) {
  const props = path.join(ep.dir, 'remotion-props', locale === 'en-US' ? 'captions.all.json' : `captions.all.${locale}.json`);
  const srt = path.join(ep.dir, 'subtitles', `${locale}.srt`);
  if (!fs.existsSync(props)) return null;
  const src = JSON.parse(fs.readFileSync(props, 'utf8'));
  const words = (src.words ?? []).filter((w) => String(w.t ?? '').trim());
  if (words.length === 0) return null;

  // a fallback span only used for the last word, or where two words share a start
  const dflt = locale === 'zh-CN' ? 200 : 300;
  const rows = words.map((w, i) => {
    const s = Math.round(Number(w.s) * 1000);
    const nxt = words[i + 1] ? Math.round(Number(words[i + 1].s) * 1000) : null;
    const e = nxt != null && nxt > s ? nxt : s + dflt;
    return { t: String(w.t).trim(), s, e, important: w.e != null };
  });

  const spans = fs.existsSync(srt) ? srtSpans(srt) : [];
  const blocks = [];
  if (spans.length) {
    // group by the cue containing each word's start; a word outside every cue joins the previous
    // block rather than being dropped — a dropped word is a silently missing caption
    let cur = [], at = -1;
    for (const r of rows) {
      let idx = spans.findIndex(([a, b]) => r.s >= a && r.s < b);
      if (idx < 0) idx = at < 0 ? 0 : at;
      if (idx !== at && cur.length) { blocks.push(cur); cur = []; }
      at = idx;
      cur.push(r);
    }
    if (cur.length) blocks.push(cur);
  } else {
    blocks.push(rows);
  }

  const script = blocks
    .map((b) => b.map((r) => `${r.t}|${r.s}|${r.e}${r.important ? '|*' : ''}`).join('\n'))
    .join('\n\n');
  const durationSec = Number(src.durationSec ?? (rows[rows.length - 1].e / 1000 + 1)).toFixed(2);
  return {
    out: path.join(ep.dir, 'remotion-props', `spoken-captions.${locale}.json`),
    json: { locale, durationSec: Number(durationSec), script },
    words: rows.length,
    marked: rows.filter((r) => r.important).length,
    lines: blocks.length,
    from: path.relative(REPO_ROOT, props),
  };
}

const tree = loadTree(REPO_ROOT);
let n = 0;
for (const ep of tree.episodes) {
  const id = ep.manifest?.video_id;
  if (only && id !== only) continue;
  for (const locale of LOCALES) {
    const r = convert(ep, locale);
    if (!r) continue;
    n++;
    console.log(`  ${id} ${locale}: ${r.words} words, ${r.marked} marked -> ${r.lines} lines`);
    if (APPLY) fs.writeFileSync(r.out, JSON.stringify(r.json, null, 2) + '\n');
  }
}
console.log(n === 0 ? '\nnothing to convert' : APPLY ? `\n${n} written` : `\n${n} convertible — re-run with --apply`);
